### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by akafen** [facebookresearch/muss#21]
I try to reproduce dataset generation. But when I run scripts/mine_sequences.py , it was always killed. I think that it could be beacuse of memory.
My hardware:
uname -a :

> Linux  4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

free -m:
>                   total        used        free      shared  buff/cache   available
> Mem:         515755      169459      275909         857       70385      342168
> Swap:         69368       51612       17756

I generate 10 ** 6 sentences, and it was killed when compute embeddings,I dont know how to fix this

**Comment by louismartin** [comment]
Hi @akafen , maybe you can reduce the number of tokens when computing laser embeddings here: https://github.com/facebookresearch/muss/blob/8b016942d9d0984866f6832594c049a189c1b46e/scripts/mine_sequences.py#L99

You can also remove the mute statement here if you think it happens when computing laser embeddings: https://github.com/facebookresearch/muss/blob/8b016942d9d0984866f6832594c049a189c1b46e/muss/laser.py#L45

**Comment by akafen** [comment]
@louismartin thanks! I will try both
