### ISSUE TITLE
mining paraphrases fails with time-out error

### ISSUE THREAD

**Issue by tannonk** [facebookresearch/muss#32]
Hi,

I'm currently trying to generate paraphrase corpora from cc_net using `mine_sequences.py` script. As a test run, I was hoping to mine sentence pairs from just a couple of cc_net corpus files (e.g. `0000/en_head.json.gz`, `0001/en_head.json.gz`). However, the job fails during mining.

I haven't been able to find any answers in the issues so far and would appreciate any guidance on solving this! I've attached the script's output and relevant log/error files. 

Disclaimer: I was trying to run this on a single NVIDIA GeForce GTX TITAN X (12GB). Not sure if that would make a difference. Are there any minimum hardware/system requirements?

Thanks in advance!

[mine_sequences.out.txt](https://github.com/facebookresearch/muss/files/8033430/mine_sequences.out.txt)
[31066_0_log.out.txt](https://github.com/facebookresearch/muss/files/8033431/31066_0_log.out.txt)
[31066_0_log.err.txt](https://github.com/facebookresearch/muss/files/8033433/31066_0_log.err.txt)

**Comment by louismartin** [comment]
Probably here: https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/scripts/mine_sequences.py#L166

**Comment by chirico85** [comment]
Hi,

I got the same problem. I could catch some of the following errors:

Error 1:
Traceback (most recent call last):
  File "/home/chirico/pycharm-2021.3.1/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 292, in _on_run
    r = self.sock.recv(1024)
OSError: [Errno 9] Bad file descriptor

Error 2:
(<class 'joblib.externals.loky.process_executor.TerminatedWorkerError'>, TerminatedWorkerError('A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.\n\nThe exit codes of the workers are {EXIT(1)}'), <traceback object at 0x7f71d30ee600>)

Error 1 occurs only once at the very beginning. Code continues however.
Error 2 appears to be due to low ressources (memory). I already reduced max_tokens to 1000 and n_encoding_jobs 
to 6. The error remains. I think I could fix this somehow but that would take too much time. 

@louismartin I followed your workarround 

> without using submitit executor.submit(func, *args) but rather func(*args)

and Computing embeddings runs, slowly, but save and less elegant. The base-index folder is getting some data.

@tannonk 
> timeout_min=2 * 60

Increasing this value did not help, since ERROR 2 occurred almost from right at the beginning.

Regards!

**Comment by louismartin** [comment]
Hi @chirico85  yes probably changing the hyperparameters can help on different hardware, however I have written this code quite some time ago so I won't be of a big help here.

**Comment by chirico85** [comment]
Unfortunately, I chose the only for me "easy" way of running the code without using submitit. It worked. I think I do not have enough ressources for running the processes in parallel.
Thanks again!

**Comment by chirico85** [comment]
Hi @louismartin ,
I managed to start mining paraphrases within submitit. However, I cannot run 2 tasks at a time, because one task already uses 68% memory of my single GPU. 
As you know 'mining paraphrases' is split into processing of batches first on CPU and then on GPU. I assumed, in case of processing 2 tasks at a time, slurm would wait to process on gpu until enough memory is available, i.e. after the first task on GPU is done. Do you know if I missed something? I described my problem [here](https://github.com/facebookincubator/submitit/issues/1689#issue-1238536835).

As an alternative way I thought about using `time.sleep(10)` right when calling `get_nearest_sentence_ids`  in `nn_search.py`.  But that does not work, because apparently both tasks sleep at the same time... Do you know how I could realize that?

Regards

**Comment by louismartin** [comment]
Hi @chirico85 
Then you should run your jobs sequentially instead of in parallel if your machine does not have the resources.
You can either remove submitit entirely an call the methods manually (e.g. call `compute_and_save_nn_batched()` directly instead of using `executor.submit`).
Or you can wait until each job is finished by calling `job.result()` just after submitting it (e.g. here https://github.com/facebookresearch/muss/blob/9a28b925c83c754d7d7a7a1966c5e4cc85355848/scripts/mine_sequences.py#L176).
